# Generated by Django 3.2.20 on 2023-07-31 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president', models.CharField(max_length=500, verbose_name='Президент')),
                ('capital', models.CharField(max_length=500, verbose_name='Столица')),
                ('language', models.CharField(max_length=500, verbose_name='Язык')),
                ('valuta', models.CharField(max_length=500, verbose_name='Валюта')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country')),
            ],
        ),
    ]
